name: Django CI/CD Azure

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9.6'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install python-dotenv psycopg2-binary  # para .env e Postgres

      - name: Run Django tests
        env:
          TARGET_ENV: 'dev'
          SECRET_KEY: 'test-secret-key'
          DBNAME: 'testdb'
          DBUSER: 'testuser'
          DBPASS: 'testpass'
          DBHOST: 'localhost'
        run: python manage.py test

      - name: Prepare production (migrations + static files)
        env:
          TARGET_ENV: 'prod'
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DEBUG: 'False'
          DBNAME: ${{ secrets.DBNAME }}
          DBUSER: ${{ secrets.DBUSER }}
          DBPASS: ${{ secrets.DBPASS }}
          DBHOST: ${{ secrets.DBHOST }}
        run: |
          python manage.py migrate --noinput
          python manage.py collectstatic --noinput

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'NOME_DO_SEU_APP'          # substitua pelo nome do App Service
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: .
