# Generated by Django 4.2.23 on 2025-10-24 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0004_remove_saldo_mes_atualizacao_remove_saldo_mes_fim_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Limite_gasto_mensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_limite', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True, verbose_name='Limite de Gasto Mensal R$')),
                ('data_definicao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data/Hora da Definição')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limites_gasto_mensal', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
